mo_main_website_index:
    path:     /
    defaults: { _controller: MoMainWebsiteBundle:MainWebSite:index }
    methods: [GET]

mo_main_website_contact:
    path:     /contact
    defaults: { _controller: MoMainWebsiteBundle:MainWebSite:contact }
    methods: [GET]


mo_main_website_products:
    path:     /products
    defaults: { _controller: MoMainWebsiteBundle:Products:list }
    methods: [GET]

mo_main_website_howto:
    path:     /howto
    defaults: { _controller: MoMainWebsiteBundle:MainWebSite:howto }
    methods: [GET]

