Mo\MainWebsiteBundle\Entity\Bill:
  type: entity
  table: bills
  id:
    id:
      type: integer
      generator: {strategy: AUTO}

  oneToOne:
    order:
      targetEntity: Order
      mappedBy: bill
  oneToMany:
    billItem:
      targetEntity: BillItem
      mappedBy: bill

  fields:

    bill_num:
      type: bigint
      options:
        unsigned: true

    company_data:
      type: string
      length: 225

    client_data:
      type: string
      length: 225

    created_time:
      type: datetime

    bill_type:
      type: string
      length: 20

    observations:
      type: text


