type: entity
table: orders
id:
  id:
    type: integer
    generator: {strategy: AUTO}

manyToOne:
  client:
    targetEntity: Client
    joinColumn:
      name: client_id
      referencedColumnName: id

oneToOne:
  bill:
    targetEntity: Bills
    inversedBy: order
    joinColumn:
      name: bill_id
      referencedColumnName: id

fields:

  delivery_address:
    type: string
    length: 225

  billing_address:
    type: string
    length: 225

  created_time:
    type: datetime

  status:
    type: string
    length: 20

  last_update:
    type: date

  observations:
    type: text


