mo_user:
    resource: "@MoUserBundle/Resources/config/routing.yml"
    prefix:   /users

mo_adm:
    resource: "@MoAdmBundle/Resources/config/routing.yml"
    prefix:   /adm

mo_main_website:
    resource: "@MoMainWebsiteBundle/Resources/config/routing.yml"
    prefix:   /
