
mo_main_website:
    resource: "@MoMainWebsiteBundle/Resources/config/routing.yml"
    prefix:   /

mo_back_panel:
    resource: "@MoAdmBundle/Resources/config/routing.yml"
    prefix:   /adm

mo_security:
    resource: "@MoSecurityBundle/Resources/config/routing.yml"
    prefix:   /security
