# TODO  TRY TO PLACE THIS IN SECURITY BUNDLE ???
security:

    encoders:
          Mo\DataBundle\Entity\User:
            algorithm: bcrypt

    providers:
        bd:
          entity:
            class: Mo\DataBundle\Entity\User
            property: username


    firewalls:

      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false

      adm:
        pattern: ^/adm
        provider: bd
        anonymous: ~
        form_login:
          login_path: mo_adm_auth
          check_path: mo_adm_auth_check
        logout:
          path: mo_adm_logout
          target: /

    access_denied_url: /

    access_control:

      - { path: ^/adm/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/adm, roles: ROLE_ADMIN }




