# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
              users:
                eloy: { password: abc123., roles: "ROLE_ADMIN"}
                mo: { password: abc123.., roles: "ROLE_USER" }
    firewalls:
      secured_area:
        pattern: ^/adm/
        logout:
          path: /security/logout
          target: /
        http_basic:
          realm: "adm zone"

    encoders:
      Symfony\Component\Security\Core\User\User: plaintext


