security:

    providers:
        in_memory:
            memory:
              users:
                eloy: { password: abc123., roles: "ROLE_ADMIN"}
                mo: { password: abc123.., roles: "ROLE_USER" }
    firewalls:

      adm:
        pattern: ^/adm/

        http_basic:
          realm: "adm zone"

    access_denied_url: /

    access_control:
      - { path: ^/adm, roles: "ROLE_ADMIN" }

    encoders:
      Symfony\Component\Security\Core\User\User: plaintext


