mo_adm_index:
    path: /
    defaults: { _controller: MoAdmBundle:Adm:index }
    methods: [GET]

mo_adm_products:
    path: /products
    defaults: { _controller: MoAdmBundle:Products:list }
    methods: [GET]

mo_adm_clients:
    path: /clients
    defaults: { _controller: MoAdmBundle:Clients:list }
    methods: [GET]


mo_adm_clients_create:
    path: /clients/create
    defaults: { _controller: MoAdmBundle:Clients:create }
    methods: [GET,POST]

mo_adm_products_create:
    path:     /products/create
    defaults: { _controller: MoAdmBundle:Products:create }
    methods: [GET,POST]

mo_adm_users:
    path: /users
    defaults: { _controller: MoAdmBundle:User:list }
    methods: [GET]

mo_adm_user_update:
    path: /users/{id}
    defaults: { _controller: MoAdmBundle:User:update }
    methods: [GET, PUT]
    requirements:
      id: \d+


mo_adm_auth:
    path: /auth
    defaults: { _controller: MoAdmBundle:Auth:form }

mo_adm_auth_check:
    path: /auth/check

mo_adm_logout:
    path: /logout



