Mo\DataBundle\Entity\Address:

  type: entity
  table: addresses
  id:
    id:
      type: integer
      generator: { strategy: AUTO}

  manyToOne:
    user:
      targetEntity: User
      inversedBy: address

  fields:
    name:
      type: string
      length: 40
    lastName:
      type: string
      length: 70
    address:
      type: string
      length: 120
    postalCode:
      type: string
      length: 20
    docId:
      type: string
      length: 30
    tlf:
      type: string
      length: 30
