Mo\DataBundle\Entity\Bill:
  type: entity
  table: bills
  lifecycleCallbacks:
      prePersist: [setCreatedAt]
      preUpdate: [setUpdatedAt]
  id:
    id:
      type: integer
      generator: {strategy: AUTO}

  oneToOne:
    order:
      targetEntity: Order
      mappedBy: bill

  manyToOne:
      user:
        targetEntity: User
        mappedBy: bill

  oneToMany:
    billItem:
      targetEntity: BillItem
      mappedBy: bill

  fields:

    billNum:
      type: bigint
      options:
        unsigned: true

    companyData:
      type: string
      length: 225

    userData:
      type: string
      length: 225

    billType:
      type: string
      length: 20

    observations:
      type: text

    createdAt:
      type: datetime
      nullable: true

    updatedAt:
      type: datetime
      nullable: true


