Mo\DataBundle\Entity\BillItem:
  type: entity
  table: bills_items
  lifecycleCallbacks:
      prePersist: [setCreatedAt]
      preUpdate: [setUpdatedAt]
  id:
    id:
      type: integer
      generator: {strategy: AUTO}

  manyToOne:
    bill:
      targetEntity: Bill
      inversedBy: billItem
      joinColumn:
        name: bill_id
        referencedColumnName: id

  oneToOne:
    product:
      targetEntity: Product
      inversedBy: BillItem
      joinColumn:
        name: product_id
        referencedColumnName: id

  fields:
    name:
      type: string
      length: 50

    description:
      type: text
      nullable: true

    quantity:
      type: integer
      options:
        unsigned: true

    price:
      type: decimal
      precision: 10
      scale: 2

    createdAt:
      type: datetime
      nullable: true

    updatedAt:
      type: datetime
      nullable: true





