Mo\DataBundle\Entity\Client:

  type: entity
  table: clients
  id:
    id:
      type: integer
      generator: { strategy: AUTO}

  oneToMany:
   order:
    targetEntity: Order
    mappedBy: client

  fields:
    name:
      type: string
      length: 40
    last_name:
      type: string
      length: 70
    address:
      type: string
      length: 120
    postal_code:
      type: string
      length: 20
    birth_date:
      type: date
    email:
      type: string
      length: 50
