Mo\DataBundle\Entity\Order:
  type: entity
  table: orders
  id:
    id:
      type: integer
      generator: {strategy: AUTO}

  manyToOne:

    user:
      targetEntity: User
      joinColumn:
        name: user_id
        referencedColumnName: id

    addressDeliver:
      targetEntity: Address
      joinColumn:
        name: deliver_address_id
        referencedColumnName: id

    addressBilling:
          targetEntity: Address
          joinColumn:
            name: billing_address_id
            referencedColumnName: id

  oneToOne:
    bill:
      targetEntity: Bill
      inversedBy: order
      joinColumn:
        name: bill_id
        referencedColumnName: id

  fields:

    createdTime:
      type: datetime

    status:
      type: string
      length: 20

    lastUpdate:
      type: date

    observations:
      type: text


