Mo\DataBundle\Entity\Order:
  type: entity
  table: orders
  lifecycleCallbacks:
      prePersist: [setCreatedAt]
      preUpdate: [setUpdatedAt]
  id:
    id:
      type: integer
      generator: {strategy: AUTO}

  manyToOne:

    user:
      targetEntity: User
      joinColumn:
        name: user_id
        referencedColumnName: id

    addressDeliver:
      targetEntity: Address
      joinColumn:
        name: deliver_address_id
        referencedColumnName: id

    addressBilling:
          targetEntity: Address
          joinColumn:
            name: billing_address_id
            referencedColumnName: id

  oneToOne:
    bill:
      targetEntity: Bill
      inversedBy: order
      joinColumn:
        name: bill_id
        referencedColumnName: id

  fields:

    status:
      type: string
      length: 20

    observations:
      type: text

    createdAt:
      type: datetime
      nullable: true

    updatedAt:
      type: datetime
      nullable: true


