Mo\DataBundle\Entity\Product:
  type: entity
  table: products
  lifecycleCallbacks:
      prePersist: [setCreatedAt]
      preUpdate: [setUpdatedAt]
  id:
    id:
      type: integer
      generator: {strategy: AUTO}

  oneToOne:
    billItem:
      targetEntity: BillItem
      mappedBy: product

  fields:

    name:
      type: string
      length: 50

    budget:
      type: decimal
      precision: 10
      scale: 2

    price:
      type: decimal
      precision: 10
      scale: 2

    tax:
      type: decimal
      precision: 10
      scale: 2

    description:
      type: text

    createdAt:
      type: datetime
      nullable: true

    updatedAt:
      type: datetime
      nullable: true

