Mo\DataBundle\Entity\User:
    type: entity
    table: users
    lifecycleCallbacks:
        prePersist: [setCreatedAt]
        preUpdate: [setUpdatedAt]
    id:
      id:
        type: integer
        generator: {strategy: AUTO}

    oneToMany:
      address:
        targetEntity: Address
        mappedBy: user

    oneToMany:
      bill:
        targetEntity: Bill
        mappedBy: user

    oneToMany:
      order:
        targetEntity: Order
        mappedBy: user

    fields:

      username:
        type: string
        length: 50

      password:
        type: string
        length: 150

      salt:
        type: string
        length: 150
        nullable: true

      email:
        type: string
        length: 150
        unique: true

      isActive:
        type: boolean

      roles:
        type: string
        length: 255

      createdAt:
        type: datetime
        nullable: true

      updatedAt:
        type: datetime
        nullable: true

