
mo_user_auth:
    path: /auth
    defaults: { _controller: MoUserBundle:Auth:form }

mo_user_auth_check:
    path: /auth/check

mo_user_logout:
    path: /logout

mo_user_index:
    path:     /
    defaults: { _controller: MoUserBundle:User:index }

mo_user_register:
    path: /create
    methods: [GET, POST]
    defaults: { _controller: MoUserBundle:User:create }

mo_user_order:
    path: /order/create
    methods: [GET, POST]
    defaults: { _controller: MoUserBundle:Order:create }