services:
  mo_user.mail_notificator:
    class: Mo\UserBundle\Model\MailNotificator
    arguments: [@mailer, @mo_user.mail_composer]
  mo_user.mail_composer:
    class: Mo\UserBundle\Model\MailComposer
    arguments: [@templating, "%app_email%"]

